### ISSUE TITLE
Would like to be a part of this github org

### ISSUE THREAD

**Issue by ucalyptus** [iem-devs/datascience#4]
cc: @koustuvsinha my email id is sayantandas30011998@gmail.com

**Comment by koustuvsinha** [comment]
invited. would you like your current github id to be invited too? (@ucalyptus )

**Comment by ucalyptus** [comment]
cc: @koustuvsinha yes dada. on the iemdatagroup as well. 
I will be taking some open source and ML flip classroom sessions for our clg juniors as not much awareness is there regarding anything except TCS jobs.

**Comment by ashunigion** [comment]
During the session please make them aware of our iem-dev slack channel.

And if they are willing to attend please inform us about the same!

It will be fun to organize the meet-up with more attendees.

**Comment by ucalyptus** [comment]
Sure @ashunigion bhaiya. I will attach the slack invite link along with a google form.
